# Generated by Django 4.0.3 on 2022-03-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurements',
            name='point_from',
            field=models.CharField(default='(,)', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurements',
            name='point_to',
            field=models.CharField(default='(,)', max_length=200),
            preserve_default=False,
        ),
    ]
